- hosts: localhost
  become: true
  vars:
    # source_key: "./.ssh/id_rsa"
    # dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False
  tasks:
    - include: tasks/core-setup.yml
    - include: tasks/develop-tools.yml
    - include: tasks/picom-setup.yml
    - include: tasks/zsh-setup.yml
    - include: tasks/nvim-setup.yml
    - include: tasks/productivity-tools.yml
    - include: tasks/desktop-tools.yml
      # Brew mach ein paar Probleme mit Python usw..
      #    - include: tasks/brew-setup.yml
    - include: tasks/office-setup.yml
    - include: tasks/docker.yml
    - include: tasks/dotfiles.yml

