- name: flat-remix ppa (ppa:daniruiz/flat-remix)
  become: yes
  apt_repository:
   repo: ppa:daniruiz/flat-remix
   state: present
   update_cache: True

- name: Install packages
  become: yes
  apt: 
    name: ['redshift-gtk', 'feh', 'lxappearance', 'flat-remix-gtk', 'arc-theme', 'gnome-tweaks', 'rofi', 'xautolock', 'i3lock']

- name: Clone i3-gnome
  ansible.builtin.git:
    repo: 'https://github.com/i3-gnome/i3-gnome.git'
    dest: "{{ lookup('env', 'HOME') }}/.tmp/i3-gnome"

- name: Build and install i3-gnome
  become: yes
  shell: "cd {{ lookup('env', 'HOME') }}/.tmp/i3-gnome && make install"

