- name: Download SDKMAN!
  get_url:
    url: "https://get.sdkman.io"
    dest: "{{ lookup('env', 'HOME') }}/.tmp/sdkman.sh"

- name: Install SDKMAN!
  become: no
  script:
    cmd: "{{ lookup('env', 'HOME') }}/.tmp/sdkman.sh"

- name: Download FNM
  get_url:
    url: "https://fnm.vercel.app/install"
    dest: "{{ lookup('env', 'HOME') }}/.tmp/fnm.sh"

- name: Install FNM
  become: no
  script:
    cmd: "{{ lookup('env', 'HOME') }}/.tmp/fnm.sh"

- name: Setup RVM Install
  become: no
  shell: 
    cmd: |
      curl -sSL https://rvm.io/mpapis.asc | gpg --import -
      curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -
      echo 409B6B1796C275462A1703113804BB82D39DC0E3:6: | gpg --import-ownertrust # mpapis@gmail.com
      echo 7D2BAF1CF37B13E2069D6956105BD0E739499BDB:6: | gpg --import-ownertrust # piotr.kuczynski@gmail.com

- name: Download RVM
  get_url:
    url: "https://get.rvm.io"
    dest: "{{ lookup('env', 'HOME') }}/.tmp/rvm.sh"

- name: Install FNM
  become: no
  script:
    cmd: "{{ lookup('env', 'HOME') }}/.tmp/rvm.sh"

- name: Download VS Code
  get_url:
    url: "https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64"
    dest: "{{ lookup('env', 'HOME') }}/.tmp/code.deb"

- name: Install VS Code
  become: yes
  apt: 
    deb: "{{ lookup('env', 'HOME') }}/.tmp/code.deb"

- name: Download kitty
  get_url:
    url: "https://sw.kovidgoyal.net/kitty/installer.sh"
    dest: "{{ lookup('env', 'HOME') }}/.tmp/kitty.sh"

- name: Install kitty
  become: no
  script:
    cmd: "{{ lookup('env', 'HOME') }}/.tmp/kitty.sh"

- name: Setup Kitty Desktop
  shell:
    cmd: |
        ln -s {{ lookup('env', 'HOME') }}/.local/kitty.app/bin/kitty {{ lookup('env', 'HOME') }}//.local/bin/
        cp {{ lookup('env', 'HOME') }}/.local/kitty.app/share/applications/kitty.desktop {{ lookup('env', 'HOME') }}/.local/share/applications/
        sed -i "s|Icon=kitty|Icon={{ lookup('env', 'HOME') }}/.local/kitty.app/share/icons/hicolor/256x256/apps/kitty.png|g" {{ lookup('env', 'HOME') }}/.local/share/applications/kitty.desktop

- name: JetBrains Toolbox
  unarchive: 
    src: https://download.jetbrains.com/toolbox/jetbrains-toolbox-1.21.9712.tar.gz
    dest: "{{ lookup('env', 'HOME') }}/.local/bin"
    remote_src: yes

