- name: Neovim Installation
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/neovim"
- name: Build neovim
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make"
- name: Install neovim
  become: yes
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make install"
- name: ensure vim directory exists
  file:
    path: "{{ lookup('env', 'HOME') }}/.vim/autoload/"
    state: directory
- name: install plug.vim
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ lookup('env', 'HOME') }}/.vim/autoload/plug.vim" 

