- name: Neovim Installation
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/neovim"
- name: Build neovim
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make"
- name: Install neovim
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make install"
