- name: Install Dependencies
  apt:
    name: [ "libxext-dev", "meson", "libxcb1-dev", "libxcb-damage0-dev", "libxcb-xfixes0-dev", "libxcb-shape0-dev", "libxcb-render-util0-dev", "libxcb-render0-dev", "libxcb-randr0-dev", "libxcb-composite0-dev", "libxcb-image0-dev", "libxcb-present-dev", "libxcb-xinerama0-dev", "libxcb-glx0-dev", "libpixman-1-dev", "libdbus-1-dev", "libconfig-dev", "libgl1-mesa-dev", "libpcre2-dev", "libpcre3-dev", "libevdev-dev", "uthash-dev", "libev-dev", "libx11-xcb-dev" ]
- name: Clone Picom
  ansible.builtin.git:
    repo: 'https://github.com/yshui/picom.git'
    dest: "{{ lookup('env', 'HOME') }}/picom"
- name: Init submodules
  shell: "cd {{ lookup('env', 'HOME') }}/picom && git submodule update --init --recursive"
- name: Meson configure
  shell: "cd {{ lookup('env', 'HOME') }}/picom && meson --buildtype=release . build"
- name: Build and Install
  shell: "cd {{ lookup('env', 'HOME') }}/picom && ninja -C build install"

