- name: kdenlive ppa (ppa:kdenlive/kdenlive-stable)
  become: yes
  apt_repository:
   repo: ppa:kdenlive/kdenlive-stable
   state: present
   update_cache: True
- name: Install packages
  become: yes
  apt: 
    name: ['tmux', 'wireshark', 'fzf', 'kdenlive', 'gimp', 'xclip', 'tldr', 'p7zip', 'p7zip-full', 'p7zip-rar']
