- name: Install ZSH
  apt: name=zsh

- name: Change shell to zsh
  become: yes
  shell: "chsh -s $(which zsh) {{ lookup('env', 'USER') }}"

- name: Download OMZ
  get_url:
    url: "https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh"
    dest: "{{ lookup('env', 'HOME') }}/.tmp/omz.sh"

- name: Install OMZ
  become: no
  script:
    cmd: "{{ lookup('env', 'HOME') }}/.tmp/omz.sh"

- name: Download Starship
  get_url:
    url: "https://starship.rs/install.sh"
    dest: "{{ lookup('env', 'HOME') }}/.tmp/starship.sh"

- name: Install Starship
  become: no
  script:
    cmd: "{{ lookup('env', 'HOME') }}/.tmp/starship.sh"

- name: Install JetBrains Mono NerdFonts
  unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/JetBrainsMono.zip
    dest: "{{ lookup('env', 'HOME') }}/.local/share/fonts"
    remote_src: yes

- name: ensure tmp directory exists
  file:
    path: "{{ lookup('env', 'HOME') }}/.tmp/JetBrainsMono/"
    state: directory

- name: Download JetBrains Mono
  unarchive:
    src: https://download.jetbrains.com/fonts/JetBrainsMono-2.242.zip
    dest: "{{ lookup('env', 'HOME') }}/.tmp/JetBrainsMono"
    remote_src: yes

- name: Install JetBrains Mono
  copy:
    src: "{{ lookup('env', 'HOME') }}/.tmp/JetBrainsMono/fonts/ttf/" 
    dest: "{{ lookup('env', 'HOME') }}/.local/share/fonts"

- name: Update font-cache
  shell: fc-cache -fv

